services:
  - type: web
    name: ai-powered-travel-planner
    runtime: python
    rootDirectory: ai-powered-travel-planner
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENROUTER_API_KEY
        sync: false
